# Generated by Django 3.0.3 on 2020-04-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0003_auto_20200329_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='image',
            field=models.ImageField(blank=True, default='/media/photos/default.jpg', upload_to='photos/'),
        ),
    ]
