# Generated by Django 3.0.3 on 2020-05-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0004_auto_20200407_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='image',
            field=models.FileField(blank=True, db_column='image_url', default='/media/photos/default.jpg', upload_to='photos/'),
        ),
    ]
