# Generated by Django 3.0.3 on 2020-05-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0005_auto_20200501_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='image',
            field=models.ImageField(blank=True, default='/media/photos/default.jpg', upload_to='photos/'),
        ),
    ]
